<h2>​​Syntax</h2>

<pre>
	<code>try($tryFunc, $catchFunc)</code>
</pre>

<h2>Beschreibung</h2>

<div>
<div>Führt eine Try-Funktion aus und behandelt auftretende Fehler durch eine Catch-Funktion. Die try-Funktion implementiert ein try-catch-Verhalten für TLScript, das eine robuste Fehlerbehandlung ermöglicht.</div>
</div>

<p>Die Funktion arbeitet mit zwei Parametern:</p>

<ol>
	<li><strong>Try-Funktion</strong>: Die auszuführende Funktion, die einen Fehler verursachen könnte</li>
	<li><strong>Catch-Funktion</strong>: Die Fallback-Funktion, die bei einem Fehler ausgeführt wird</li>
</ol>

<div>
<div>Bei erfolgreicher Ausführung der try-Funktion wird deren Ergebnis zurückgegeben. Tritt ein Fehler auf, wird die catch-Funktion mit spezifischen Parametern ausgeführt:</div>

<ul>
	<li><strong>I18NException</strong>: catch-Funktion erhält (ResKey, ursprüngliches Argument)</li>
	<li><strong>Reguläre Exception</strong>: catch-Funktion erhält (Fehlermeldung, ursprüngliches Argument)</li>
</ul>
</div>

<h2>Paramter</h2>

<table class="tlDocTable" style="height:155px; width:1517px">
	<thead>
		<tr>
			<th>Bezeichnung</th>
			<th>Typ</th>
			<th>Beschreibung</th>
			<th>Pflicht</th>
			<th>Standard</th>
		</tr>
		<tr>
			<td>
			<p>tryFunc</p>
			</td>
			<td>Funktion</td>
			<td>Die Funktion, die ausgeführt werden soll.</td>
			<td>ja</td>
			<td>-</td>
		</tr>
		<tr>
			<td>catchFunc</td>
			<td>Funktion</td>
			<td>Die Fallback-Funktion, die bei einem Fehler ausgeführt wird. Erhält das Exception-Objekt als Parameter</td>
			<td>nein</td>
			<td>null</td>
		</tr>
	</thead>
</table>

<h2>Rückgabewert</h2>

<p><strong>Typ:</strong> Object</p>

<div>
<div>Gibt das Ergebnis der try-Funktion zurück, wenn diese erfolgreich ausgeführt wurde. Bei einem Fehler wird das Ergebnis der catch-Funktion zurückgegeben. Ist keine catch-Funktion angegeben, wird bei einem Fehler <code class="hljs inlineCode">null</code>zurückgegeben.</div>
</div>

<h2>Beispiele</h2>

<pre>
	<code>try(
  sendMail(
    subject: $subject,
    to: $emailAddr,
    body: $emailBody
  ),
  catchFun: mailError -&gt; {
    info("E-Mail-Zustellung an " + $emailAddr + " fehlgeschlagen. Grund: " + $mailError);
    false
  }
)</code>
</pre>

<p><strong>Ausgabe: </strong>Versucht eine E-Mail zu senden. Bei Erfolg wird das Ergebnis von <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">sendMail</code> zurückgegeben. Bei einem Fehler wird <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">false</code> zurückgegeben und eine Benutzerinfo mit der versuchten E-Mail-Adresse.</p>
